apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ExternalAdmissionHookConfiguration
metadata:
  name: container-analysis-webhook
externalAdmissionHooks:
  - name: image-signature.hightowerlabs.com
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    failurePolicy: Ignore
    clientConfig:
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURsRENDQW55Z0F3SUJBZ0lVSUlpWEY0TDFCZWdIMlJLMktUcy9qMUJlQ01zd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1lqRUxNQWtHQTFVRUJoTUNWVk14RHpBTkJnTlZCQWdUQms5eVpXZHZiakVSTUE4R0ExVUVCeE1JVUc5eQpkR3hoYm1ReEVEQU9CZ05WQkFvVEIwZHlZV1psWVhNeEN6QUpCZ05WQkFzVEFrTkJNUkF3RGdZRFZRUURFd2RICmNtRm1aV0Z6TUI0WERURTNNVEV6TURJek1UVXdNRm9YRFRJeU1URXlPVEl6TVRVd01Gb3dZakVMTUFrR0ExVUUKQmhNQ1ZWTXhEekFOQmdOVkJBZ1RCazl5WldkdmJqRVJNQThHQTFVRUJ4TUlVRzl5ZEd4aGJtUXhFREFPQmdOVgpCQW9UQjBkeVlXWmxZWE14Q3pBSkJnTlZCQXNUQWtOQk1SQXdEZ1lEVlFRREV3ZEhjbUZtWldGek1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXBFSFRXWWEwdlEvTUo0RUNWZnJYNk9CUXZUaEYKbzg3SWV2YmVkVlVXYm5jMzhFTnFoSk8yWWdLNE9vSnhZdTRobXE3NEN3R25hZ1ZialQ3MGxoSHhHVm5MNS8xcwpPVzZYcWhYOXlBUURTTXVJa3ZXK3V0Y0FCL1ZxVlVpTFJLR0NnTmgwWW8zWVVnbG44L05Vb3ZjejFTenY3bFFGCmw1cXpJVUtTd05VM2NpM2ZOYmpMOFd0K3VrSE0xT3lvcGE1aktGblhlYWk3SGRndWxrenFQUFNudlNtcktiV1gKc01seDV1K2g4T2doN2ZLQkxLS3hIdjFFOTlSMjNWWFlnajdXWUovR2dRSmNpYnJKUk9hTXJyTHFLVTJmUDVUUQpMbDBrZ1Nrc3dwUFhkU3pydXdOZElqL28zd0J0bk9YOWV0NVM1WjFadWlJWFo5YUtST2NKbFRzQ29RSURBUUFCCm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FRWXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUKWHNiNnR3YXJpeHhIR045RmdDQ1MwaVZIN0tRd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFJTHZ5VkxmY3hxZQoyNSttdWVwUUZucnNwbUdFNEluNjgySlNUclZzcEh2NkFqZXpkRlJobSsxSzZNckRodEdzTGJsZUkybE8xZHlpCkVqL21JK2RRcjhrVnY1QXJYRjhXSnVsYXNnUzh6bVJDREVSM3hhcG55emh3QUdvVnhSc01GODU0Z090SXRvNE8KelZ4VTkzS29QemtwMEpzN1dRNmRnLzVqSCtiWTBjbXN6UHBwTmJSaXdsb2F5NVduZG5JeHYxUFNKNzU5emVWQQpBU1FoNm8rV1ZxcFFrYjdOS0Jvc0ZTTENwTUN0T1NETGJzRWY1dFNGRzF4NXhFNHhWSFl1OVVYSjR1K3pOT2d3CjFUcUE0L3Jkd0I3WUcvTFFsSlNrMC85V2RKemtCYkNIam1KQ0ZTQXZjQzM2QU03aHlBNTJ0SkV2S2JYb2p2aVEKdndsZTZvbjloVTQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      service:
        name: container-analysis-webhook
        namespace: default
