apiVersion: v1
kind: Service
metadata:
  labels:
    app: container-analysis-webhook
  name: container-analysis-webhook
spec:
  ports:
    - name: https
      port: 443
      protocol: "TCP"
  selector:
    app: container-analysis-webhook
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: container-analysis-webhook
spec:
  template:
    metadata:
      labels:
        app: container-analysis-webhook
    spec:
      containers:
        - name: container-analysis-webhook
          image: "gcr.io/google-demos/container-analysis-webhook:0.1.0"
          imagePullPolicy: Always
          args:
            - "-tls-cert=/etc/admission-controller/tls/tls.crt"
            - "-tls-key=/etc/admission-controller/tls/tls.key"
          volumeMounts:
            - name: tls
              mountPath: /etc/admission-controller/tls
            - name: pubkeys
              mountPath: /etc/admission-controller/pubkeys
      volumes:
        - name: tls
          secret:
            secretName: tls-container-analysis-webhook
        - name: pubkeys
          configMap:
            name: container-analysis-webhook
